version: '3.8'

services:
  adonis_app:
    container_name: DJU
    build:
      context: .
      target: dependencies
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
    volumes:
      - ./:/app
    links:
      - 'postgres'
    command: node ace serve --watch --node-args="--inspect=0.0.0.0"

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
      POSTGRES_DB: ${POSTGRES_DB:-dju}
      POSTGRES_HOST_AUTH_METHOD: md5
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  postgres:
    driver: local
